use ner::ner_service_client::NerServiceClient;
use ner::NerRequest;


// This macro pulls in the code generated by tonic-build
pub mod ner {
    tonic::include_proto!("ner");
}


#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut client  = NerServiceClient::connect("http://[::1]:50051").await?;

    let req = tonic::Request::new(NerRequest {
        text: "Apple is looking at buying a startup in the UK".to_string(),
    });

    let resp = client.extract_entities(req).await?;

    println!("RESPONSE={:?}", resp);

    for entity in resp.into_inner().entities {
        println!(
            "Entity: {} | Label: {} | Range: {}-{}",
            entity.text, entity.label, entity.start, entity.end
        );
    }

    Ok(())

}



