# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ml_server_proto.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ml_server_proto.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15ml_server_proto.proto\x12\nml_service\"8\n\x15\x43lassificationRequest\x12\x11\n\tprompt_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"U\n\x16\x43lassificationResponse\x12\x11\n\tprompt_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x1a\n\x12is_prompt_injected\x18\x03 \x01(\x08\x32w\n\x1bPromptClassificationService\x12X\n\x0f\x43lassifyPrompts\x12!.ml_service.ClassificationRequest\x1a\".ml_service.ClassificationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_server_proto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLASSIFICATIONREQUEST']._serialized_start=37
  _globals['_CLASSIFICATIONREQUEST']._serialized_end=93
  _globals['_CLASSIFICATIONRESPONSE']._serialized_start=95
  _globals['_CLASSIFICATIONRESPONSE']._serialized_end=180
  _globals['_PROMPTCLASSIFICATIONSERVICE']._serialized_start=182
  _globals['_PROMPTCLASSIFICATIONSERVICE']._serialized_end=301
# @@protoc_insertion_point(module_scope)
