# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ner_proto.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ner_proto.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fner_proto.proto\x12\x03ner\"\x1a\n\nNERRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"A\n\x06\x45ntity\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\r\n\x05start\x18\x03 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x04 \x01(\x05\",\n\x0bNERResponse\x12\x1d\n\x08\x65ntities\x18\x01 \x03(\x0b\x32\x0b.ner.Entity2B\n\nNERService\x12\x34\n\x0f\x45xtractEntities\x12\x0f.ner.NERRequest\x1a\x10.ner.NERResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ner_proto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NERREQUEST']._serialized_start=24
  _globals['_NERREQUEST']._serialized_end=50
  _globals['_ENTITY']._serialized_start=52
  _globals['_ENTITY']._serialized_end=117
  _globals['_NERRESPONSE']._serialized_start=119
  _globals['_NERRESPONSE']._serialized_end=163
  _globals['_NERSERVICE']._serialized_start=165
  _globals['_NERSERVICE']._serialized_end=231
# @@protoc_insertion_point(module_scope)
